### ISSUE TITLE
The viterbi decoding implementation may be wrong

### ISSUE THREAD

**Issue by jiqiujia** [jiesutd/NCRFpp#134]
I look into the viterbi decoding implementation and find that when backtracing the best path, argmax is done based on the current emission probability + previous score + transition probability. If my understanding is correct, the argmax should be done only based on previous score + transition probability, which is also suggested by [wikipedia](https://en.wikipedia.org/wiki/Viterbi_algorithm) and the official crf implementation [crf](https://pytorch.org/tutorials/beginner/nlp/advanced_tutorial.html). Please clarify this.

**Comment by jiesutd** [comment]
Hi @jiqiujia , it is not wrong. This implementation does not affect the final result. During the argmax,  the emission score for each tag is the same, so it does not affect the final result. It is just a different implementation.

You can also find this comment at the official CRF implementation
`# We don't include the emission scores here because the max`
 `# does not depend on them (we add them in below)`
