### ISSUE TITLE
Why is test_dir included in the training config?

### ISSUE THREAD

**Issue by taasmoe** [jiesutd/NCRFpp#141]
I've noticed some [earlier issues](https://github.com/jiesutd/NCRFpp/issues/61) concerning the use of the test set for initializing vocabularies. 

Even if it won't affect the performance, why should we monitor the test results during training?

Thanks

**Comment by jiesutd** [comment]
Because in the beginning, I didn't implement the model saving module, so monitor test result is necessary to report your experiment results. 

But as now the model saving module has been implemented, it is your personal choice to decide whether to monitor the test data during training. For me, I keep it because I am lazy and I don't  want to add an extra step of loading the model and decode test.

I have checked and confirmed it does not affect the model performance. Just for convinience.
