### ISSUE TITLE
-1 Precision, Recall and F1 Score

### ISSUE THREAD

**Issue by Killthebug** [jiesutd/NCRFpp#80]
Hi,

Even after running for multiple epochs (>15), I get the precision, recall and F1 score to be -1. The data I'm working with is in the BIO format. 

The train config file : https://pastebin.com/XGqpW6HD
Output log : https://pastebin.com/9G6kfJ2f

Weird element in output log : gold_num =  0  pred_num =  0  right_num =  0

Train Dataset Size : 50063 Tokens
Val Dataset Size : 5563 Tokens
Test Dataset Size : 4970 Tokens

The loss does seem to going down, so the model is learning but the predicted results messed up.

Note : Although the data is formatted in the BIO format, there are no 'I' tags for this instance of the dataset. Could that be causing an issue here?

Regards

**Comment by jiesutd** [comment]
The training process works ok, you can see the acc keeps increasing and can over 96% on test data, which means the model works well.

The golden num is 0 in your log file. So I am pretty sure that the problem is your data format. The PRF is used for segment task such as NER or Word segmentation. If your task does not care about the segment acc (e.g. POS task), you can set ‘seg=False’ in your configure file.

**Comment by Killthebug** [comment]
Thanks for the prompt response!
It's a task similar to NER and hence, segment acc does matter. Any other idea regarding how I can tackle this problem. 
Here is a link to the test-set : https://pastebin.com/uhXwrfLT

**Comment by jiesutd** [comment]
Only label ‘B’ and ‘O’ ? If you real care about the RPF, then replace the ‘B’ label as ‘B-X’. It will works.

**Comment by Killthebug** [comment]
Thank you for the help! It works now.
